name: Build-Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  Build-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build rootless image
        run: ./build-rootless.sh $(echo $GITHUB_REPOSITORY |cut -d '/' -f1)
      - name: Build standard image
        run: ./build.sh $(echo $GITHUB_REPOSITORY |cut -d '/' -f1)
      - name: List Docker images
        run: docker images --filter "reference=puppet-dev-tools*" --filter "reference=*/puppet-dev-tools*"
      - name: Show Docker image labels
        run: |
          docker inspect --format='{{json .Config.Labels}}' ${{ secrets.DOCKERHUB_USERNAME }}/puppet-dev-tools
      - name: Run tests
        working-directory: ${{ github.workspace }}/tests
        run: ./run_tests.sh
